version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - 8000:80
    volumes:
      -  ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  
  app1: 
    build: ./
    restart: always
    ports:
      - 80:80
    env_file: 
      - .env
    container_name: app1
    networks:
      - app-network
  
  app2: 
    build: ./
    restart: always
    ports:
      - 85:80
    env_file: 
      - .env
    container_name: app2
    networks:
      - app-network

  pubSub:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge